### ISSUE TITLE
Integrate with SonarCloud

### ISSUE THREAD

**Issue by mwz** [sonar-scala/sonar-scala#134]
https://sonarcloud.io/coding_rules?languages=scala

**Comment by mwz** [comment]
Hi, are you asking whether 1. this plugin is scanned and reporting results to SonarCloud or 2. whether one can use this plugin in SonarCloud?

the answer is no to both:

1. We were planning to integrate with SonarCloud to get the plugin accepted to the SonarQube Marketplace, but we got rejected since SonarSource didn't want any competition in this space (see [here](https://community.sonarsource.com/t/sonar-scala-a-new-plugin-for-scala/1082) for more context).
2. Only official plugins developed by SonarSource are enabled in SonarCloud, so you can't use any community plugins there.

**Comment by angelcervera** [comment]
>     1. We were planning to integrate with SonarCloud to get the plugin accepted to the SonarQube Marketplace, but we got rejected since SonarSource didn't want any competition in this space (see [here](https://community.sonarsource.com/t/sonar-scala-a-new-plugin-for-scala/1082) for more context).

Looks like a mafia. 😄
