### ISSUE TITLE
Can't get junit report to work with test coverage

### ISSUE THREAD

**Issue by Symbianx** [sonar-scala/sonar-scala#672]
Hello,
Thanks for all the amazing work put into this plugin, it's extremely useful!

I managed to get the statement coverage and code smell reports working in sonarqube but I'm failing to get the number of unit tests run working.

Our project uses sbt and generates the test reports as expected but I can't seem to get all the sonar sensors working at the same time.

Am I doing anything wrong here? Is this not a supported use case?

What I tried so far follows:

### First try
Setting the following properties result in the code coverage and code smells being reported in sonarqube but not the test execution report (how many failed, how many succeded, etc):
```
" -D sonar.scala.scoverage.reportPath='out/scoverage-report/scoverage.xml'" +
" -D sonar.scala.scapegoat.reportPath='out/scapegoat-report/scapegoat.xml'" +
" -D sonar.junit.reportPaths='out/test-reports'" +
" -D sonar.verbose=true"
```
The debug output prints
```
DEBUG: 'Scala JUnit Sensor' skipped because there is no related file in current project
[...]
Sensors : CSS Rules -> Scala Sensor -> Scalastyle Sensor -> Scapegoat Sensor -> Scoverage Sensor -> Go Cover sensor for Go coverage -> JaCoCo XML Report Importer -> C# Properties -> JavaXmlSensor -> HTML -> XML Sensor -> VB.NET Properties
```

### Second try
To the existing properties I tried adding the `sonar.tests` property pointing to the test directory which results in the unit test execution being report, but now the all scala sensors except the JUnit Report are not executed at all:
```
" -D sonar.tests='src/test/scala/taxonomy'" +
" -D sonar.scala.scoverage.reportPath='out/scoverage-report/scoverage.xml'" +
" -D sonar.scala.scapegoat.reportPath='out/scapegoat-report/scapegoat.xml'" +
" -D sonar.junit.reportPaths='out/test-reports'" +
" -D sonar.verbose=true"
```
The debug output includes
```
DEBUG: 'Scalastyle Sensor' skipped because there is no related file in current project
DEBUG: 'Scapegoat Sensor' skipped because there is no related file in current project
DEBUG: 'Scoverage Sensor' skipped because there is no related file in current project
[...]
DEBUG: Sensors : CSS Rules -> Scala Sensor -> Scala JUnit Sensor -> Go Cover sensor for Go coverage -> JaCoCo XML Report Importer -> C# Properties -> JavaXmlSensor -> VB.NET Properties
```

**Comment by Symbianx** [comment]
Hi @mwz,
Thanks for the quick response!
After setting the `sonar.tests` to `src/test/scala`, it still didn't work. Our tests are all in the `src/test/scala/taxonomy` directory. After moving the tests to `src/test/scala` junit report sensor seems to pick them up.

I also had to set `sonar.sources` to `src/main/scala` for the code smells and coverage scanning to work and it picked up the source files inside the `src/main/scala/taxonomy` folder without a problem.

Is having the test files inside a sub directories not a supported use case or is it a bug? If it is a bug, I wouldn't mind helping with a PR if you can point me in the right direction.

**Comment by mwz** [comment]
> Is having the test files inside a sub directories not a supported use case or is it a bug? If it is a bug, I wouldn't mind helping with a PR if you can point me in the right direction.

From what I remember those test reports contain package names not directory structure, so your folder structure needs to reflect your package naming for the sensor to recognise those test files - so if your package name is `taxonomy` and all your tests are inside `src/test/scala/taxonomy` setting `sonar.tests` to `src/test/scala` should work fine, unless perhaps you're missing package declarations in your test files, but the files are still located within the `taxonomy` directory, which could potentially break this. I can't think of anything else right now, but if that isn't the issue then it would definitely help if you could put together a minimal example project to replicate this issue and I'd be happy to take a look and maybe we can get to the bottom of this, it might as well be a bug in the [JUnitSensor](https://github.com/sonar-scala/sonar-scala/blob/master/src/main/scala/com/mwz/sonar/scala/junit/JUnitSensor.scala) or the [JUnitReportParser](https://github.com/sonar-scala/sonar-scala/blob/master/src/main/scala/com/mwz/sonar/scala/junit/JUnitReportParser.scala).

**Comment by Symbianx** [comment]
Wow, you're absolutely right. My test file was missing the package declaration... 🤦 
Thanks so much for all the help @mwz !

**Comment by mwz** [comment]
no worries, glad you got that sorted out!
