### ISSUE TITLE
Sonar 8.9 LTS support

### ISSUE THREAD

**Issue by h-ngo** [sonar-scala/sonar-scala#706]
@mwz is there an ETA for a new release to support Sonar 8.9 LTS?

**Comment by mwz** [comment]
Soonish hopefully; I haven't had much time lately - sorry to keep you waiting.

**Comment by h-ngo** [comment]
Thanks for the quick response.

How likely will it be released within a month? we are doing some analysis for the upgrade. Kinda want to know the time frame so we can decide whether to consider the official Sonar Scala from Sonarqube as a backup, which certainly will take more times to migrate.

**Comment by mwz** [comment]
> How likely will it be released within a month?

Quite likely I'll get around to doing that within the next week or two, so shouldn't be too long.

**Comment by h-ngo** [comment]
great! Thanks a lot.

**Comment by h-ngo** [comment]
Hi @mwz 
Do you happen to have any update?

**Comment by mwz** [comment]
Apologies for the delay. Just released https://github.com/sonar-scala/sonar-scala/releases/tag/v8.9.0, docker images should be available within a day or so.
